### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by thecodeboy** [EasyDB-io/Golang#1]
Hi Jake and Tyson,

I think it'd be better to change this repo's name to `easydbGo` or something. Cause I read the below in the [docs](https://golang.org/doc/code.html),

> Go's convention is that the package name is the last element of the import path: the package imported as "crypto/rot13" should be named rot13.

I'm new to Go, so let me know if I'm mistaken. Also I can try making this client in the weekend if no one does a pull request by then.

Cheers.

**Comment by JakeCooper** [comment]
Hey thanks for the comment. We've gone ahead and changed since that does make more sense.

I've put one up for now. Feel free to make a pull/re-open issues if you see any problems with it.
